services:
  php:
    volumes:
      - ./src:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    environment:
      - XDEBUG_MODE=debug
      - XDEBUG_CONFIG=client_host=host.docker.internal

  composer:
    volumes:
      - ./src:/app
      - composer_cache:/tmp/cache
    working_dir: /app
    command: install --no-interaction --optimize-autoloader
