services:
  # Serviço PHP com Apache
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: websocket-ratchet-php
    ports:
      - "8080:80"
      - "8082:8080" # Porta para WebSocket
    volumes:
      - ./src:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=websocket_ratchet
      - DB_USERNAME=root
      - DB_PASSWORD=password
    networks:
      - websocket-ratchet-network

  # Serviço MySQL
  mysql:
    image: mysql:8.0
    container_name: websocket-ratchet-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: websocket_ratchet
      MYSQL_USER: websocket_user
      MYSQL_PASSWORD: websocket_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - websocket-ratchet-network

  # Serviço phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: websocket-ratchet-phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      - mysql
    networks:
      - websocket-ratchet-network

  # Serviço Composer (para instalar dependências)
  composer:
    image: composer:latest
    container_name: websocket-ratchet-composer
    volumes:
      - ./src:/app
      - composer_cache:/tmp/cache
    working_dir: /app
    command: install
    networks:
      - websocket-ratchet-network

volumes:
  mysql_data:
  composer_cache:

networks:
  websocket-ratchet-network:
    driver: bridge
